#!/usr/bin/env bash

DIRBIN=`dirname $0`
DIRPROY=$DIRBIN/..
DIRAPP=$DIRPROY/app
DIRBD=$DIRPROY/bd
ARCHIVO_NOMBRE_PROYECTO="$DIRAPP/nombre_proyecto"

if [ -f $ARCHIVO_NOMBRE_PROYECTO ];
then
  NOMBREPROYECTO=$(cat $ARCHIVO_NOMBRE_PROYECTO)

  DOCKERCOMPOSEFILE=$DIRAPP/docker-compose.yml
  COMPOSERFILE=$DIRAPP/composer.json

  DOCKERCOMPOSEFILE_OK=$(grep "<NOMBRE\ PROYECTO>" $DOCKERCOMPOSEFILE)
  COMPOSERFILE_OK=$(grep "siu-toba\/template-proyecto-toba" $COMPOSERFILE)

  if [ ! "$DOCKERCOMPOSEFILE_OK" ];
  then
    echo "Error: $DOCKERCOMPOSEFILE: no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
    exit 1
  fi
  if [ ! "$COMPOSERFILE_OK" ];
  then
    echo "Error: $COMPOSERFILE no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
    exit 1
  fi

  cp $DOCKERCOMPOSEFILE $COMPOSERFILE $DIRBIN/aux/

  sed -i "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $DOCKERCOMPOSEFILE

  # siu-toba/template-proyecto-toba
  sed -i "s/siu-toba\/template-proyecto-toba/$NOMBREPROYECTO/g" $COMPOSERFILE

  rm $ARCHIVO_NOMBRE_PROYECTO

  exit 0
fi

echo "No se puede nombrar el proyecto porque no existe el archivo '$ARCHIVO_NOMBRE_PROYECTO'"
exit 1
