DROP DATABASE IF EXISTS "<NOMBRE BASEDEDATOS>";

CREATE DATABASE "<NOMBRE BASEDEDATOS>"
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'C'
       LC_CTYPE = 'C'
       CONNECTION LIMIT = -1
       TEMPLATE template0;
